{
  Type: Exception,
  Message: The Message,
  StackTrace:
at Tests.TaskMethodThatThrowsGeneric()
at InnerVerifier.ThrowsTask[T](Func`1 target)
}