{
  Type: Exception,
  Message: The Message,
  StackTrace:
at Tests.Nested.MethodThatThrows()
at InnerVerifier.Throws(Action target)
}